# Generated by Django 4.2.6 on 2025-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('GR_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date_of_admission', models.DateField()),
                ('admission_class', models.CharField(max_length=50)),
                ('current_class', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('medium', models.CharField(choices=[('Sindhi', 'Sindhi'), ('Urdu', 'Urdu'), ('English', 'English')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('district_of_birth', models.CharField(max_length=100)),
                ('taluka_of_birth', models.CharField(max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('parent_cnic', models.CharField(max_length=15, unique=True)),
                ('cell_no', models.CharField(max_length=15)),
                ('nadra_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
