# Generated by Django 4.2.6 on 2025-01-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_date_of_school_leaving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/images/', verbose_name='Profile Image'),
        ),
    ]
