# Generated by Django 4.2.6 on 2025-09-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_class_studied',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
