# Generated by Django 4.2.6 on 2025-09-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_last_class_studied'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='conduct',
            field=models.CharField(blank=True, default='Good', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='progress',
            field=models.CharField(blank=True, default='Good', max_length=100, null=True),
        ),
    ]
