# Generated by Django 4.2.6 on 2025-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_conduct_student_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seat_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
