# Generated by Django 4.2.6 on 2025-09-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_seat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Supplementary', 'Supplementary')], default='Annual', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='medium',
            field=models.CharField(choices=[('Sindhi', 'Sindhi'), ('Urdu', 'Urdu'), ('English', 'English')], default='Sindhi', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Non-Muslim', 'Non-Muslim')], default='Muslim', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
