# Generated by Django 4.2.6 on 2025-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_exam_month_student_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Private', 'Private')], default='Regular', max_length=50),
        ),
    ]
