# Generated by Django 4.2.6 on 2025-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('personal_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Personal Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('bps', models.IntegerField(verbose_name='BPS')),
                ('cnic', models.CharField(max_length=15, verbose_name='CNIC')),
                ('account_no', models.CharField(max_length=30, verbose_name='Account Number')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualification')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_appointment', models.DateField(blank=True, null=True, verbose_name='Date of Appointment')),
                ('date_of_school_joining', models.DateField(verbose_name='Date of School Joining')),
            ],
        ),
    ]
