# Generated by Django 4.2.6 on 2025-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_of_school_leaving',
            field=models.DateField(blank=True, null=True, verbose_name='Date of School Leaving'),
        ),
    ]
